[project]
name = "pyhashbench"
version = "0.1.1"
description = "A comprehensive testing library for your hash functions"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy", "scipy"]
